import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { ethers } from "ethers";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
    console.log("Deploying ReliqueX contract via ethers...");

    const provider = new ethers.JsonRpcProvider("http://127.0.0.1:8545");
    const signer = await provider.getSigner();

    const artifactPath = path.join(__dirname, "../artifacts/contracts/ReliqueX.sol/ReliqueX.json");
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));

    const factory = new ethers.ContractFactory(artifact.abi, artifact.bytecode, signer);
    const reliquex = await factory.deploy();

    await reliquex.waitForDeployment();
    const address = await reliquex.getAddress();
    console.log("ReliqueX deployed to:", address);

    const outputDir = path.join(__dirname, "../../src/lib/web3");
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    const content = `// Auto-generated by Hardhat deploy script
export const reliqueXAddress = "${address}";
export const reliqueXABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

    fs.writeFileSync(path.join(outputDir, "contract.ts"), content);
    console.log("ABI and address saved to src/lib/web3/contract.ts");
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
